[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
panic = "abort"
